/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 05-7月-2023 17:48:49 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `gw_request_logs` CASCADE
;

DROP TABLE IF EXISTS `myservice` CASCADE
;

DROP TABLE IF EXISTS `running_params` CASCADE
;

DROP TABLE IF EXISTS `rzqx_organization` CASCADE
;

DROP TABLE IF EXISTS `rzqx_sys` CASCADE
;

DROP TABLE IF EXISTS `rzqx_user` CASCADE
;

DROP TABLE IF EXISTS `rzqx_user_organization` CASCADE
;

DROP TABLE IF EXISTS `service_agreement` CASCADE
;

DROP TABLE IF EXISTS `service_category` CASCADE
;

DROP TABLE IF EXISTS `service_control` CASCADE
;

DROP TABLE IF EXISTS `service_demand` CASCADE
;

DROP TABLE IF EXISTS `service_evaluation` CASCADE
;

DROP TABLE IF EXISTS `service_evaluation_system` CASCADE
;

DROP TABLE IF EXISTS `service_evaluation_users` CASCADE
;

DROP TABLE IF EXISTS `service_index` CASCADE
;

DROP TABLE IF EXISTS `service_logs_check` CASCADE
;

DROP TABLE IF EXISTS `service_logs_request` CASCADE
;

DROP TABLE IF EXISTS `service_resource` CASCADE
;

DROP TABLE IF EXISTS `service_resource_externed` CASCADE
;

DROP TABLE IF EXISTS `service_stat_day_check` CASCADE
;

DROP TABLE IF EXISTS `service_stat_day_request` CASCADE
;

DROP TABLE IF EXISTS `service_tags` CASCADE
;

DROP TABLE IF EXISTS `service_type` CASCADE
;

DROP TABLE IF EXISTS `service_whitelist` CASCADE
;

DROP TABLE IF EXISTS `sjzy_database` CASCADE
;

DROP TABLE IF EXISTS `sjzy_dataset` CASCADE
;

DROP TABLE IF EXISTS `sjzy_field` CASCADE
;

DROP TABLE IF EXISTS `sjzy_tree` CASCADE
;

DROP TABLE IF EXISTS `sys_dict_item` CASCADE
;

/* Create Tables */

CREATE TABLE `gw_request_logs`
(
	`id` VARCHAR(64) NOT NULL COMMENT '旧ID,无序',
	`user_id` VARCHAR(100) NULL COMMENT '用户ID',
	`app_id` VARCHAR(100) NULL COMMENT '应用ID',
	`service_id` VARCHAR(100) NULL COMMENT '服务资源标识',
	`request_ip` VARCHAR(255) NULL COMMENT '请求方IP',
	`request_url` VARCHAR(500) NULL COMMENT '服务地址',
	`request_time` TIMESTAMP(3) NULL COMMENT '服务请求时间',
	`request_method` VARCHAR(64) NULL COMMENT '请求方式',
	`request_original_header` VARCHAR(50) NULL,
	`request_original_param` LONGTEXT NULL COMMENT '原始请求参数',
	`request_head_param` LONGTEXT NULL COMMENT '请求头内容',
	`request_param` LONGTEXT NULL COMMENT '处理后请求参数',
	`forward_url` VARCHAR(500) NULL COMMENT '服务访问地址,服务实际跳转地址',
	`forward_time` TIMESTAMP(3) NULL COMMENT '转发时间',
	`forward_state` VARCHAR(20) NULL COMMENT '服务转发状态',
	`forward_fail_reason` VARCHAR(4000) NULL COMMENT '服务转发失败原因',
	`response_time` TIMESTAMP(3) NULL COMMENT '服务响应时间',
	`response_original_header` VARCHAR(50) NULL,
	`response_original_param` LONGTEXT NULL COMMENT '原始响应请求',
	`response_header` VARCHAR(50) NULL,
	`response_param` LONGTEXT NULL COMMENT '处理后响应请求',
	`response_state` VARCHAR(20) NULL COMMENT '服务响应状态',
	`create_time` TIMESTAMP(3) NULL COMMENT '创建时间',
	CONSTRAINT `PK_gw_request_logs` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '服务请求日志表'

;

CREATE TABLE `myservice`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`service_name` VARCHAR(100) NULL,
	`classify` INT NULL,
	`version` VARCHAR(50) NULL,
	`label` VARCHAR(500) NULL COMMENT '服务标签',
	`status` INT NULL,
	`starttime` DATETIME NULL,
	`endtime` DATETIME NULL,
	`count_day` INT NULL,
	`count_total` INT NULL,
	`count_called` INT NULL,
	`create_time` DATETIME NULL,
	`is_del` INT NULL,
	`service_type` INT NULL,
	CONSTRAINT `PK_myservice` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `running_params`
(
	`key` VARCHAR(255) NOT NULL,
	`value` VARCHAR(1024) NULL,
	CONSTRAINT `PK_running_params` PRIMARY KEY (`key` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET latin1
COLLATE latin1_swedish_ci

;

CREATE TABLE `rzqx_organization`
(
	`id` VARCHAR(64) NOT NULL,
	`parent_id` VARCHAR(64) NULL,
	`name` VARCHAR(64) NULL,
	`code` VARCHAR(64) NULL,
	CONSTRAINT `PK_rzqx_organization` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `rzqx_sys`
(
	`id` VARCHAR(64) NOT NULL,
	`name` VARCHAR(255) NULL,
	`description` VARCHAR(512) NULL,
	`version` VARCHAR(8) NULL,
	`url` VARCHAR(512) NULL,
	CONSTRAINT `PK_rzqx_sys` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `rzqx_user`
(
	`id` VARCHAR(64) NOT NULL,
	`name` VARCHAR(50) NULL,
	`password` VARCHAR(50) NULL,
	`account` VARCHAR(50) NULL,
	`level` VARCHAR(8) NULL,
	`roles` VARCHAR(1024) NULL COMMENT '包含角色信息：
	[{roleid,rolename},...]',
	`constraint_ip` VARCHAR(255) NULL COMMENT '最多5个，逗号分隔',
	`constraint_mac` VARCHAR(255) NULL COMMENT '最多5个，逗号分隔',
	`police_type` VARCHAR(50) NULL,
	`police_code` VARCHAR(50) NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `rzqx_user_organization`
(
	`id` VARCHAR(64) NOT NULL,
	`organization_id` VARCHAR(64) NULL
)

;

CREATE TABLE `service_agreement`
(
	`id` VARCHAR(100) NOT NULL,
	`service_agreement_identifier` VARCHAR(100) NULL COMMENT '服务规约标识',
	`service_agreement_name` VARCHAR(100) NULL,
	`service_agreement_desc` VARCHAR(1000) NULL,
	`service_agreement_version` VARCHAR(10) NULL,
	`service_agreement_orgid` VARCHAR(100) NULL,
	`service_agreement_orgname` VARCHAR(100) NULL,
	`service_definition_info` VARCHAR(1000) NULL,
	`service_definition_content` VARCHAR(1000) NULL,
	`service_resp_code` VARCHAR(1000) NULL,
	`service_agreement_createtime` DATETIME NULL,
	`is_deleted` INT NULL DEFAULT 0,
	`service_file_name` VARCHAR(1000) NULL COMMENT '接口名称-',
	`service_file_description` VARCHAR(1000) NULL,
	`service_file_interfaceurl` VARCHAR(1000) NULL,
	`service_file_reqway` VARCHAR(1000) NULL,
	`service_file_reqparam` VARCHAR(1000) NULL COMMENT '请求参数',
	`service_file_respparam` VARCHAR(1000) NULL COMMENT '响应参数',
	`service_file_respdefine` VARCHAR(1000) NULL COMMENT '响应码定义',
	`wsdlxml` VARCHAR(4000) NULL,
	CONSTRAINT `PK_service_agreement` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `service_category`
(
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '服务分类id',
	`parent_id` INT NULL COMMENT '父级id',
	`service_category` VARCHAR(50) NULL COMMENT '服务分类',
	`create_userid` VARCHAR(32) NULL COMMENT '创建人id',
	`create_username` VARCHAR(32) NULL COMMENT '创建人',
	`create_time` TIMESTAMP NULL COMMENT '创建时间',
	CONSTRAINT `PK_service_category` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '服务分类表'

;

CREATE TABLE `service_control`
(
	`id` VARCHAR(64) NOT NULL,
	`service_apply_id` VARCHAR(32) NULL,
	`service_resource_id` VARCHAR(32) NULL,
	`strategy_category` INT NULL,
	`strategy_source` INT NULL,
	`strategy_type` VARCHAR(32) NULL,
	`moment_strategy_unit` INT NULL,
	`moment_strategy_nums` INT NULL,
	`flow_strategy_single` INT NULL,
	`flow_strategy_total` INT NULL,
	`data_strategy_single` INT NULL,
	`data_strategy_total` INT NULL,
	`download_strategy_single` INT NULL,
	`download_strategy_total` INT NULL,
	`data_opt_userid` VARCHAR(32) NULL,
	`data_opt_username` VARCHAR(32) NULL,
	`data_opt_time` DATETIME NULL,
	`is_deleted` INT NULL DEFAULT 0,
	`form_data` VARCHAR(4000) NULL,
	CONSTRAINT `PK_service_control` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `service_demand`
(
	`id` VARCHAR(32) NOT NULL,
	`service_proposer_name` VARCHAR(100) NULL,
	`service_proposer_desc` VARCHAR(1000) NULL,
	`service_category_id` INT NULL,
	`service_type_id` INT NULL,
	`service_proposer_userid` VARCHAR(32) NULL,
	`service_proposer_username` VARCHAR(32) NULL,
	`service_proposer_orgid` VARCHAR(100) NULL,
	`service_proposer_orgname` VARCHAR(100) NULL,
	`service_proposer_contact` VARCHAR(100) NULL,
	`relation_data_resource_identifier` VARCHAR(1000) NULL,
	`service_req_args` VARCHAR(4000) NULL,
	`service_resp_args` VARCHAR(4000) NULL,
	`service_proposer_creator_id` VARCHAR(32) NULL,
	`service_proposer_creator_name` VARCHAR(32) NULL,
	`service_proposer_time` DATETIME NULL,
	`service_proposer_approve_time` DATETIME NULL,
	`service_proposer_approve_userid` VARCHAR(32) NULL,
	`service_proposer_approve_username` VARCHAR(100) NULL,
	`service_proposer_status` INT NULL COMMENT '字典码(1未构建、2构建中、3已构建)',
	`service_build_id` VARCHAR(32) NULL,
	`is_deleted` INT ZEROFILL UNSIGNED NOT NULL COMMENT '0未删除，1已删除，默认为0',
	CONSTRAINT `PK_service_demand` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '服务需求'

;

CREATE TABLE `service_evaluation`
(
	`id` VARCHAR(32) NOT NULL,
	`service_name` VARCHAR(64) NULL COMMENT '服务资源名称',
	`service_version` VARCHAR(32) NULL COMMENT '服务版本',
	`service_type` INT NULL COMMENT '服务类型',
	`score` VARCHAR(32) NULL COMMENT '总得分',
	`evaluate_num` INT NOT NULL COMMENT '参评人数',
	`evaluate_score` VARCHAR(32) NULL COMMENT '使用方得分',
	`system_score` VARCHAR(32) NULL COMMENT '系统得分',
	`service_provider` VARCHAR(32) NULL COMMENT '服务提供方',
	`service_provider_orgname` VARCHAR(255) NULL COMMENT '服务提供方名称',
	`update_time` DATETIME NULL COMMENT '最近更新时间',
	CONSTRAINT `PK_service_evaluation` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '服务评分表'

;

CREATE TABLE `service_evaluation_system`
(
	`id` VARCHAR(32) NOT NULL,
	`service_evaluation_id` VARCHAR(32) NULL COMMENT '服务评价iD',
	`index_id` VARCHAR(32) NULL COMMENT '指标ID',
	`value` VARCHAR(255) NULL COMMENT '指标值',
	`score` VARCHAR(32) NULL COMMENT '指标得分',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_service_evaluation_system` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '系统评价得分'

;

CREATE TABLE `service_evaluation_users`
(
	`id` VARCHAR(32) NOT NULL,
	`service_evaluation_id` VARCHAR(32) NULL COMMENT '服务评价ID',
	`user_id` VARCHAR(32) NULL COMMENT '用户ID',
	`user_name` VARCHAR(255) NULL COMMENT '用户名称',
	`evaluation_content` VARCHAR(255) NULL COMMENT '评价内容',
	`score` INT NULL COMMENT '评分',
	`evaluation_time` DATETIME NULL COMMENT '评价时间',
	`status` INT NULL COMMENT '0:删除，1：正常，2：隐藏',
	`new_evaluation` VARCHAR(255) NULL COMMENT '0:否，1：是',
	CONSTRAINT `PK_service_evaluation_users` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '客观评价得分'

;

CREATE TABLE `service_index`
(
	`id` VARCHAR(32) NOT NULL,
	`name` VARCHAR(32) NULL COMMENT '指标名称',
	`description` VARCHAR(300) NULL COMMENT '指标描述',
	`index_type` INT NULL COMMENT '1.可用性
	2.可靠性
	3.响应性',
	`status` INT NULL COMMENT '1:启用 0：停用',
	`evaluation_type` INT NULL COMMENT '1:系统评价，2：使用方法评价',
	`rule` VARCHAR(512) NULL COMMENT '规则',
	CONSTRAINT `PK_service_index` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '服务统计指标管理'

;

CREATE TABLE `service_logs_check`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`service_id` VARCHAR(32) NULL COMMENT '服务资源编号',
	`fault_num` BIGINT NULL DEFAULT 0 COMMENT '今日故障次数',
	`stat_time` DATETIME NULL COMMENT '统计时间',
	CONSTRAINT `PK_service_fault` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = 'service_fault
1、支持压缩的心跳日志
2、支持安全性能的统计'

;

CREATE TABLE `service_logs_request`
(
	`logID` BIGINT NOT NULL COMMENT '日志ID',
	`requestIp` VARCHAR(255) NULL COMMENT '请求方IP',
	`userId` VARCHAR(100) NULL COMMENT '用户ID',
	`policeType` VARCHAR(64) NULL COMMENT '用户警种',
	`account` VARCHAR(50) NULL COMMENT '用户账号',
	`username` VARCHAR(50) NULL COMMENT '用户名称',
	`rolenames` VARCHAR(1000) NULL COMMENT '用户角色',
	`organizationname` VARCHAR(100) NULL COMMENT '用户组织',
	`appId` VARCHAR(100) NULL COMMENT '应用ID',
	`sysname` VARCHAR(50) NULL COMMENT '应用简称',
	`sysdescription` VARCHAR(100) NULL COMMENT '应用名称',
	`serviceId` VARCHAR(100) NULL COMMENT '服务编号',
	`resourceId` VARCHAR(64) NULL COMMENT '服务资源ID',
	`serviceResourceName` VARCHAR(100) NULL COMMENT '服务资源名称',
	`serviceGatewayUrl` VARCHAR(1000) NULL COMMENT '服务URL',
	`requestMethod` VARCHAR(100) NULL COMMENT '请求方式',
	`serviceResourceProviderSysid` VARCHAR(100) NULL COMMENT '提供方系统ID',
	`serviceResourceProviderSysname` VARCHAR(100) NULL COMMENT '提供方系统名称',
	`dataset` VARCHAR(255) NULL COMMENT '注册数据集ID',
	`datasetName` VARCHAR(255) NULL COMMENT '注册数据集名称',
	`dataResourceIDs` VARCHAR(512) NULL COMMENT '数据集ID',
	`dataResourceNames` VARCHAR(255) NULL COMMENT '数据集名称',
	`requestTime` TIMESTAMP NULL COMMENT '请求时间',
	`requestHeadParam` LONGTEXT NULL COMMENT '请求头内容',
	`requestParam` LONGTEXT NULL COMMENT '请求体内容',
	`requestDataNum` INT NULL COMMENT '数据请求数据量',
	`forwardCost` INT NULL COMMENT '转发耗时',
	`forwardState` VARCHAR(20) NULL COMMENT '转发状态',
	`forwardFailReason` VARCHAR(1000) NULL COMMENT '转发失败信息',
	`responseCost` INT NULL COMMENT '响应耗时',
	`responseState` VARCHAR(20) NULL COMMENT '响应状态',
	`responseDataNum` INT NULL COMMENT '响应数据量',
	`responseParam` LONGTEXT NULL COMMENT '响应体内容',
	CONSTRAINT `PK_gw_request_logs` PRIMARY KEY (`logID` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `service_resource`
(
	`id` VARCHAR(32) NOT NULL COMMENT ' 编号',
	`service_build_id` VARCHAR(32) NULL COMMENT ' 服务构建id',
	`service_resource_identifier` VARCHAR(32) NULL COMMENT ' 服务资源标识符',
	`service_resource_name` VARCHAR(100) NULL COMMENT ' 服务资源名称',
	`service_resource_desc` VARCHAR(1000) NULL COMMENT ' 服务资源描述',
	`service_resource_version` VARCHAR(32) NULL COMMENT ' 服务资源版本',
	`service_category_id` INT NULL COMMENT ' 服务分类编号',
	`service_type_id` INT NULL COMMENT ' 服务类型编号',
	`service_resource_url` VARCHAR(1000) NULL COMMENT ' 服务资源访问地址',
	`service_gateway_url` VARCHAR(1000) NULL COMMENT ' 资源网关访问地址',
	`service_call_type` INT NULL COMMENT ' 请求类型1:REST',
	`service_resource_method` VARCHAR(100) NULL COMMENT '请求方式（POST/GET..)',
	`relation_data_resource_identifier` VARCHAR(1000) NULL COMMENT ' 关联数据资源标识符',
	`service_req_args` LONGTEXT NULL COMMENT ' 请求参数(接口输入参数)',
	`service_resp_args` LONGTEXT NULL COMMENT ' 响应参数(接口输出参数)',
	`service_req_sample` LONGTEXT NULL COMMENT ' 请求参数样例(接口输入参数)',
	`service_resp_code` LONGTEXT NULL COMMENT ' 响应状态码',
	`service_resource_doc` VARCHAR(1000) NULL COMMENT ' 接口文档',
	`service_resource_status` INT NULL COMMENT ' 服务资源状态',
	`service_resource_open` INT NULL COMMENT ' 是否公开',
	`service_resource_report` INT NULL COMMENT ' 是否上报',
	`service_resource_reg_userid` VARCHAR(32) NULL COMMENT ' 服务注册者id',
	`service_resource_reg_username` VARCHAR(32) NULL COMMENT ' 服务注册者姓名',
	`service_resource_reg_time` DATETIME NULL COMMENT ' 服务注册时间',
	`service_resource_provider_orgid` VARCHAR(32) NULL COMMENT ' 服务提供方组织机构编号',
	`service_resource_provider_orgname` VARCHAR(100) NULL COMMENT ' 服务提供方组织机构名称',
	`service_resource_provider_sysid` VARCHAR(32) NULL COMMENT ' 提供服务资源的应用系统编号',
	`service_resource_provider_sysname` VARCHAR(100) NULL COMMENT ' 提供服务资源的应用系统名称',
	`service_resource_off_time` DATETIME NULL COMMENT ' 服务下架时间',
	`service_resource_off_reason` VARCHAR(1000) NULL COMMENT ' 服务下架原因',
	`service_resource_off_userid` VARCHAR(32) NULL COMMENT ' 下架申请人id',
	`service_resource_off_username` VARCHAR(32) NULL COMMENT ' 下架申请人姓名',
	`service_resource_origin_type` INT NULL COMMENT ' 服务来源类型',
	`resource_catalog_id` VARCHAR(32) NULL COMMENT ' 资源目录id',
	`service_agreement_id` VARCHAR(32) NULL COMMENT ' 服务规约编号',
	`service_power_orgid` VARCHAR(32) NULL COMMENT ' 服务事权机构id',
	`service_power_orgname` VARCHAR(100) NULL COMMENT ' 服务事权机构名称',
	`service_power_userid` VARCHAR(32) NULL COMMENT ' 事权责任人id',
	`service_power_username` VARCHAR(32) NULL COMMENT ' 事权责任人姓名',
	`service_power_contact` VARCHAR(100) NULL COMMENT ' 事权责任人联系方式',
	`service_mgmt_orgid` VARCHAR(32) NULL COMMENT ' 服务管理机构id',
	`service_mgmt_orgname` VARCHAR(100) NULL COMMENT ' 服务管理机构名称',
	`service_mgmt_userid` VARCHAR(32) NULL COMMENT ' 管理责任人id',
	`service_mgmt_username` VARCHAR(32) NULL COMMENT ' 管理责任人姓名',
	`service_mgmt_contact` VARCHAR(100) NULL COMMENT ' 管理责任人联系方式',
	`data_reg_orgid` VARCHAR(32) NULL COMMENT ' 信息登记单位id',
	`data_reg_orgname` VARCHAR(100) NULL COMMENT ' 信息登记单位名称',
	`data_reg_userid` VARCHAR(32) NULL COMMENT ' 信息登记人员id',
	`data_reg_username` VARCHAR(32) NULL COMMENT ' 信息登记人员姓名',
	`data_reg_idcard` VARCHAR(32) NULL COMMENT ' 信息登记人员身份证号',
	`data_opt_orgid` VARCHAR(32) NULL COMMENT ' 信息操作单位id',
	`data_opt_orgname` VARCHAR(100) NULL COMMENT ' 信息操作单位名称',
	`data_opt_userid` VARCHAR(32) NULL COMMENT ' 信息操作人员id',
	`data_opt_username` VARCHAR(32) NULL COMMENT ' 信息操作人员姓名',
	`data_opt_idcard` VARCHAR(32) NULL COMMENT ' 信息操作人员身份证号',
	`service_inout_type` INT NULL DEFAULT 1 COMMENT '服务类型1 内部服务 2 外部服务',
	`service_release_dept` VARCHAR(32) NULL COMMENT '发布单位',
	`service_releaser` VARCHAR(32) NULL COMMENT '发布人',
	`service_release_num` VARCHAR(32) NULL COMMENT '发布人警号',
	`service_release_phone` VARCHAR(32) NULL COMMENT '发布人手机号',
	`service_interface_url` VARCHAR(100) NULL COMMENT '服务地址，模板内',
	`service_topic` VARCHAR(32) NULL COMMENT '服务主题',
	`is_deleted` INT NULL DEFAULT 0 COMMENT ' 是否逻辑删除',
	`service_req_headers` VARCHAR(2000) NULL,
	`service_resp_headers` VARCHAR(2000) NULL,
	`service_resp_sample` LONGTEXT NULL,
	`oneselfuse` VARCHAR(1) NULL COMMENT '是否自用',
	`service_agent_sys_id` VARCHAR(32) NULL COMMENT ' 服务中介_应用系统编码',
	`service_provide_type` VARCHAR(1) NULL COMMENT '服务提供方式1：API网关',
	`is_asyn_service` VARCHAR(2) NULL DEFAULT 0,
	CONSTRAINT `PK_service_resource` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `service_resource_externed`
(
	`id` VARCHAR(64) NOT NULL COMMENT '唯一标识',
	`service_resource_identifier` VARCHAR(32) NOT NULL COMMENT ' 服务资源标识符',
	`param_name` VARCHAR(32) NOT NULL COMMENT '扩展类型:token_request',
	`param_value` TEXT NULL COMMENT '不同扩展的参数体',
	CONSTRAINT `PK_service_resource_externed` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET latin1
COLLATE latin1_swedish_ci
COMMENT = '1、安全验证的参数内容
2、日志记录配置内容'

;

CREATE TABLE `service_stat_day_check`
(
	`service_id` VARCHAR(32) NOT NULL COMMENT '服务资源编号',
	`run_time` BIGINT NULL COMMENT '无故障运行时长（m）',
	`fault_num` BIGINT NULL DEFAULT 0 COMMENT '累计故障次数',
	`fault_total_time` BIGINT NULL COMMENT '累计故障时长/服务恢复时长（m）',
	`first_time` BIGINT NULL COMMENT '第一次故障时长（m）',
	`second_time` BIGINT NULL COMMENT '第二次故障时长（m）',
	`third_time` BIGINT NULL COMMENT '第三次故障时长（m）',
	`run_status` INT NULL COMMENT '检测状态0：异常，1正常',
	`update_time` DATETIME NULL COMMENT '更新时间',
	CONSTRAINT `PK_service_performance_stat` PRIMARY KEY (`service_id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '服务性能统计表'

;

CREATE TABLE `service_stat_day_request`
(
	`statID` VARCHAR(32) NOT NULL COMMENT 'ͳ��ID,����������MD5',
	`requestIp` VARCHAR(255) NULL COMMENT '����IP',
	`userId` VARCHAR(100) NULL COMMENT '�û�ID',
	`policeType` VARCHAR(64) NULL COMMENT '�û�����',
	`account` VARCHAR(50) NULL COMMENT '�û��˺�',
	`username` VARCHAR(50) NULL COMMENT '�û�����',
	`rolenames` VARCHAR(1000) NULL COMMENT '�û���ɫ',
	`organizationname` VARCHAR(100) NULL COMMENT '�û���֯',
	`appId` VARCHAR(100) NULL COMMENT 'Ӧ��ID',
	`sysname` VARCHAR(50) NULL COMMENT 'Ӧ�ü��',
	`sysdescription` VARCHAR(100) NULL COMMENT 'Ӧ������',
	`serviceId` VARCHAR(100) NULL COMMENT '������',
	`resourceId` VARCHAR(64) NULL COMMENT '������ԴID',
	`serviceResourceName` VARCHAR(100) NULL COMMENT '������Դ����',
	`serviceGatewayUrl` VARCHAR(1000) NULL COMMENT '����URL',
	`requestMethod` VARCHAR(100) NULL COMMENT '����ʽ',
	`serviceResourceProviderSysid` VARCHAR(100) NULL COMMENT '�ṩ��ϵͳID',
	`serviceResourceProviderSysname` VARCHAR(100) NULL COMMENT '�ṩ��ϵͳ����',
	`dataset` VARCHAR(255) NULL COMMENT 'ע�����ݼ�ID',
	`datasetName` VARCHAR(255) NULL COMMENT 'ע�����ݼ�����',
	`dataResourceIDs` VARCHAR(512) NULL COMMENT '���ݼ�ID',
	`dataResourceNames` VARCHAR(255) NULL COMMENT '���ݼ�����',
	`requestDate` VARCHAR(32) NOT NULL COMMENT '����ʱ�䣨�죩',
	`forwardState` VARCHAR(20) NULL COMMENT 'ת��״̬',
	`forwardFailReason` VARCHAR(1000) NULL COMMENT 'ת��ʧ����Ϣ',
	`responseState` VARCHAR(20) NULL COMMENT '��Ӧ״̬',
	`requestCount` INT NULL COMMENT '����������',
	`requestNewerTime` VARCHAR(20) NULL COMMENT '���ʹ��ʱ��',
	`requestDataNum` INT NULL COMMENT '��������������',
	`forwardAvgCost` DOUBLE(22,0) NULL COMMENT 'ƽ��ת��ʱ��(00.00)',
	`responseAvgCost` DOUBLE(22,0) NULL COMMENT 'ƽ����Ӧʱ��(00.00)',
	`responseDataNum` INT NULL COMMENT '��Ӧ������',
	CONSTRAINT `PK_service_stat_day_request_log` PRIMARY KEY (`statID` ASC, `requestDate` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `service_tags`
(
	`id` VARCHAR(32) NOT NULL COMMENT '编号',
	`pid` VARCHAR(32) NULL COMMENT '父级编号',
	`tag_name` VARCHAR(32) NULL COMMENT '标签名称',
	`tag_desc` VARCHAR(100) NULL COMMENT '标签描述',
	`order_num` INT NULL DEFAULT 0 COMMENT '排序号',
	`is_tag_category` VARCHAR(2) NULL COMMENT '是否是标签分类：1 是；0 不是（即标签）',
	`is_use` VARCHAR(2) NULL COMMENT '1：启用；0：停用',
	`create_userid` VARCHAR(32) NULL COMMENT '创建人id',
	`create_username` VARCHAR(32) NULL COMMENT '创建人',
	`create_time` TIMESTAMP NULL COMMENT '创建时间',
	CONSTRAINT `PK_tag_info` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `service_type`
(
	`id` INT NOT NULL AUTO_INCREMENT COMMENT '服务类型id',
	`service_category_id` INT NULL COMMENT '服务分类表id',
	`service_type_BB` VARCHAR(8) NULL COMMENT '服务类型的部标码',
	`service_type` VARCHAR(50) NULL COMMENT '服务类型',
	`service_type_desc` VARCHAR(255) NULL COMMENT '服务类型说明',
	`is_use` VARCHAR(2) NULL COMMENT '1：启用；0：停用',
	`create_userid` VARCHAR(32) NULL COMMENT '创建人id',
	`create_username` VARCHAR(32) NULL COMMENT '创建人',
	`create_time` TIMESTAMP NULL COMMENT '创建时间',
	CONSTRAINT `PK_service_type` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '服务类型表'

;

CREATE TABLE `service_whitelist`
(
	`id` VARCHAR(32) NOT NULL COMMENT '编号',
	`orgid` VARCHAR(32) NULL COMMENT '所属组织机构id',
	`orgname` VARCHAR(100) NULL COMMENT '所属组织机构名称',
	`userid` VARCHAR(32) NULL COMMENT '用户id',
	`username` VARCHAR(32) NULL COMMENT '用户名称',
	`status` INT NULL DEFAULT 2 COMMENT '状态 （1：启用2：停用）',
	`opt_userid` VARCHAR(32) NULL COMMENT '操作人员id',
	`opt_username` VARCHAR(32) NULL COMMENT '操作人员姓名',
	`sysid` VARCHAR(32) NULL COMMENT '应用编码',
	`sysname` VARCHAR(100) NULL,
	`opt_time` DATETIME NULL COMMENT '最新操作时间',
	`type` INT NULL COMMENT '字典码(1 用户白名单、2 应用白名单)',
	`is_deleted` INT NULL DEFAULT 0,
	CONSTRAINT `PK_white_list_control` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

CREATE TABLE `sjzy_database`
(
	`id` BIGINT NOT NULL COMMENT '主键唯一标识',
	`source_name` VARCHAR(100) NOT NULL COMMENT '数据来源名称',
	`source_desc` VARCHAR(100) NULL COMMENT '数据源说明',
	`db_name` VARCHAR(50) NULL COMMENT '数据库名称',
	`db_type` VARCHAR(30) NOT NULL COMMENT '数据库类型',
	`host_name` VARCHAR(50) NOT NULL COMMENT '主机名称',
	`port` VARCHAR(50) NOT NULL COMMENT '端口号',
	`user_name` VARCHAR(50) NOT NULL COMMENT '用户名',
	`user_pwd` VARCHAR(50) NULL COMMENT '用户密码',
	`connect_param` VARCHAR(50) NOT NULL,
	`connect_status` INT NULL DEFAULT 1 COMMENT '连接状态 1 未连接 2 连接正常 3 连接异常 ',
	`sid` VARCHAR(50) NULL,
	`set_status` INT NULL DEFAULT 1 COMMENT '1 未配置 2 配置中 3 配置完成',
	`count` INT NULL DEFAULT 0 COMMENT '表数量',
	`origin_dept` VARCHAR(100) NOT NULL COMMENT '来源部门',
	`origin_sys` VARCHAR(50) NULL COMMENT '来源系统',
	`contacts` VARCHAR(50) NULL COMMENT '联系人 如 张三',
	`phone` VARCHAR(50) NULL COMMENT '联系电话',
	`firm` VARCHAR(50) NOT NULL COMMENT '厂商  如：北京锐安科技',
	`status` INT NULL DEFAULT 0 COMMENT '0 启用 1 停用',
	`explore_status` INT NULL DEFAULT 1 COMMENT '探查状态 1 未探查 2 探查中  3 探查完成 4 探查异常',
	`create_time` TIMESTAMP NULL DEFAULT NULL on update CURRENT_TIMESTAMP COMMENT '创建时间',
	`connect_time` BIGINT NULL COMMENT '测试连接时间',
	CONSTRAINT `PK_sjzy_database` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '数据源管理'

;

CREATE TABLE `sjzy_dataset`
(
	`id` BIGINT NOT NULL,
	`datasource_id` BIGINT NULL,
	`dataset_schema` VARCHAR(50) NULL,
	`dataset_enname` VARCHAR(100) NULL,
	`dataset_cnname` VARCHAR(100) NULL,
	`data_count` INT NULL,
	`field_count` INT NULL,
	`status` INT NULL DEFAULT 0 COMMENT '0隐藏,1显示',
	`complete_time` TIMESTAMP NULL,
	`update_time` TIMESTAMP(4) NULL,
	`user` VARCHAR(50) NULL,
	`source_type` INT NULL COMMENT '来源方式：1数据库探查，2文件导入',
	`explore_status` INT NULL COMMENT '0探查中1 探查成功 2 探查失败 3 导入成功',
	`dataset_desc` VARCHAR(1000) NULL,
	`finish_status` VARCHAR(1) NULL DEFAULT '0' COMMENT '填写状态：1：完成  0 未完成',
	`example_data` VARCHAR(1000) NULL,
	CONSTRAINT `PK_sjzy_dataset` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '数据源数据集'

;

CREATE TABLE `sjzy_field`
(
	`id` BIGINT NOT NULL,
	`dataset_id` BIGINT NULL COMMENT '来源表ID',
	`chname` VARCHAR(100) NULL COMMENT '中文名',
	`enname` VARCHAR(100) NULL COMMENT '英文名',
	`field_type` VARCHAR(50) NULL COMMENT '字段类型',
	`length` VARCHAR(50) NULL COMMENT '字段长度',
	`filling_rate` VARCHAR(60) NULL COMMENT '填充率',
	`status` INT NULL DEFAULT 1 COMMENT '状态 1 启用 2 停用',
	`sort` INT NULL DEFAULT 0 COMMENT '排序',
	`remark` VARCHAR(100) NULL COMMENT '备注',
	`dic_code` VARCHAR(64) NULL COMMENT '字典码',
	`data_relate` VARCHAR(64) NULL COMMENT '字段抽取相关字段',
	`field_constraint` VARCHAR(64) NULL COMMENT '字段约束',
	`create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`column_status` INT NULL DEFAULT 0 COMMENT '0初始字段 1 新增 2 删除',
	`mark_type` VARCHAR(255) NULL COMMENT '要素类型',
	`is_null` INT NULL COMMENT '是否为空,0:非空，1：可空',
	`is_primary_key` INT NULL COMMENT '是否主键',
	`is_partition` INT NULL COMMENT '是否分区字段',
	`default_value` VARCHAR(255) NULL COMMENT '默认值',
	`is_show` VARCHAR(1) NULL COMMENT '是否显示： 1 显示 0 不显示',
	CONSTRAINT `PK_sjzy_field` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci
COMMENT = '数据集对应的字段'

;

CREATE TABLE `sjzy_tree`
(
	`DRID` VARCHAR(50) NOT NULL,
	`parent_DRID` VARCHAR(50) NULL,
	`DR_name` VARCHAR(50) NULL,
	`DR_node` VARCHAR(50) NULL,
	`DR_remark` VARCHAR(512) NULL,
	`engine_tag` VARCHAR(50) NULL,
	`database_id` VARCHAR(50) NULL,
	`dataset_id` VARCHAR(50) NULL,
	CONSTRAINT `PK_sjzy_tree` PRIMARY KEY (`DRID` ASC)
)

;

CREATE TABLE `sys_dict_item`
(
	`id` VARCHAR(36) NOT NULL COMMENT 'ID主键',
	`itemcode` TEXT NULL COMMENT '字典编码',
	`itemvalue` TEXT NULL COMMENT '字典值',
	`itemname` TEXT NULL COMMENT '字典值对应名称',
	`remark` TEXT NULL COMMENT '备注：扩展字段',
	`description` TEXT NULL COMMENT '字典项说明',
	CONSTRAINT `PK_sys_dict_item` PRIMARY KEY (`id` ASC)
)
ENGINE=InnoDB
DEFAULT CHARSET utf8
COLLATE utf8_general_ci

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `gw_request_logs` 
 ADD INDEX `forward_status` (`forward_state` ASC)
;

ALTER TABLE `gw_request_logs` 
 ADD INDEX `request_time` (`request_time` ASC)
;

ALTER TABLE `gw_request_logs` 
 ADD INDEX `user_id` (`user_id` ASC)
;

ALTER TABLE `gw_request_logs` 
 ADD INDEX `app_id` ()
;

ALTER TABLE `running_params` 
 ADD INDEX `idx_key` (`key` ASC)
;

ALTER TABLE `service_agreement` 
 ADD CONSTRAINT `idx_uniq_id` UNIQUE (`id` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_account` (`account` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_appId` (`appId` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_dataResourceIDs` (`dataResourceIDs` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_dataResourceNames` (`dataResourceNames` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_dataset` (`dataset` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_datasetName` (`datasetName` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_forwardFailReason` (`forwardFailReason` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_forwardState` (`forwardState` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_organizationname` (`organizationname` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_policeType` (`policeType` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_requestDataNum` (`requestDataNum` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_requestIp` (`requestIp` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_requestMethod` (`requestMethod` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_requestTime` (`requestTime` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_resourceId` (`resourceId` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_responseState` (`responseState` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_rolenames` (`rolenames` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_serviceGatewayUrl` (`serviceGatewayUrl` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_serviceId` (`serviceId` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_serviceResourceName` (`serviceResourceName` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_serviceResourceProviderSysid` (`serviceResourceProviderSysid` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_serviceResourceProviderSysname` (`serviceResourceProviderSysname` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_sysdescription` (`sysdescription` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_sysname` (`sysname` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_userId` (`userId` ASC)
;

ALTER TABLE `service_logs_request` 
 ADD INDEX `idx_username` (`username` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_account` (`account` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_appId` (`appId` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_dataResourceIDs` (`dataResourceIDs` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_dataResourceNames` (`dataResourceNames` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_dataset` (`dataset` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_datasetName` (`datasetName` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_forwardFailReason` (`forwardFailReason` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_forwardState` (`forwardState` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_organizationname` (`organizationname` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_policeType` (`policeType` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_requestDate` (`requestDate` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_requestIp` (`requestIp` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_requestMethod` (`requestMethod` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_resourceId` (`resourceId` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_responseState` (`responseState` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_rolenames` (`rolenames` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_serviceGatewayUrl` (`serviceGatewayUrl` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_serviceId` (`serviceId` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_serviceResourceName` (`serviceResourceName` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_serviceResourceProviderSysid` (`serviceResourceProviderSysid` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_serviceResourceProviderSysname` (`serviceResourceProviderSysname` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_sysdescription` (`sysdescription` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_sysname` (`sysname` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_userId` (`userId` ASC)
;

ALTER TABLE `service_stat_day_request` 
 ADD INDEX `idx_username` (`username` ASC)
;

SET FOREIGN_KEY_CHECKS=1
; 
